--Audit control table 
USE HRDB;
DROP TABLE HRDB_SYS_AUDIT_CONTROL;
CREATE TABLE HRDB_SYS_AUDIT_CONTROL
(OP_ID INT PRIMARY KEY AUTO_INCREMENT,  
SOURCE_NAME VARCHAR(30),
TARGET_NAME VARCHAR(30),
PROCESS_NAME VARCHAR(30),
OPERATION_TYPE VARCHAR(50),
SOURCE_COUNT INT,
TARGET_COUNT INT,
LOG_DETAILS VARCHAR(50),
OPERATED_BY VARCHAR(20),
OPERATION_DATE TIMESTAMP);