CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_TRANS_STG_TO_HOP1`()
BEGIN

/*In this step we are going to manipulate the data from the employees staging 
table to hop1 table*/
INSERT INTO TBL_TRANS_EMPLOYEES_HOP1
SELECT 
EMPLOYEE_ID,
FIRST_NAME,
LAST_NAME,
LOWER(CONCAT(EMAIL,'@PLANMEDIA.COM')) EMAIL,
PHONE_NUMBER,
HIRE_DATE,
JOB_ID,
SALARY,
IFNULL(COMMISSION_PCT,0) COMMISSION_PCT,
MANAGER_ID,
DEPARTMENT_ID
FROM TBL_STG_EMPLOYEES;


/*Here we are going to add the changes as per the department table*/

INSERT INTO TBL_TRANS_DEPARTMENTS_HOP1
SELECT * FROM TBL_STG_DEPARTMENTS;

INSERT INTO TBL_TRANS_DEPARTMENTS_HOP1 VALUES (1000,'Bench',100,NULL);

UPDATE TBL_TRANS_DEPARTMENTS_HOP1
SET MANAGER_ID=100
WHERE MANAGER_ID IS NULL;


/*Here we are going to add the changes as per the locations table*/

INSERT INTO TBL_TRANS_LOCATIONS_HOP1
SELECT * FROM TBL_STG_LOCATIONS;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET CITY='Rome'
WHERE CITY='Roma';

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='Lazio'
WHERE LOCATION_ID=1000;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='Veneto'
WHERE LOCATION_ID=1100;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='Hiroshima'
WHERE LOCATION_ID=1300;


UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='Beijing'
WHERE LOCATION_ID=2000;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET CITY='Mumbai'
WHERE LOCATION_ID=2100;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='Singapore'
WHERE LOCATION_ID=2300;

UPDATE TBL_TRANS_LOCATIONS_HOP1
SET STATE_PROVINCE='England'
WHERE LOCATION_ID in (2400,2500);

END