/*THIS IS THE HOP1 TRANSFORMATION AREA, WHERE WE ARE GOING TO MODIFY 
THE EXISTING COLUMNS BASED ON THE REQUIREMENTS DATA*/
USE HRDB;
DROP TABLE TBL_TRANS_EMPLOYEES_HOP1;
CREATE TABLE TBL_TRANS_EMPLOYEES_HOP1
(
EMPLOYEE_ID INT,
FIRST_NAME VARCHAR(45),
LAST_NAME VARCHAR(45),
EMAIL VARCHAR(50),
PHONE_NUMBER VARCHAR(13),
HIRE_DATE DATE,
JOB_ID VARCHAR(10),
SALARY DECIMAL(10,2),
COMMISSION_PCT DECIMAL(3,2),
MANAGER_ID INT,
DEPARTMENT_ID INT
);


DROP TABLE TBL_TRANS_DEPARTMENTS_HOP1;
CREATE TABLE TBL_TRANS_DEPARTMENTS_HOP1
(
DEPARTMENT_ID INT,
DEPARTMENT_NAME VARCHAR(45),
MANAGER_ID INT,
LOCATION_ID INT
); 

DROP TABLE TBL_TRANS_LOCATIONS_HOP1;
CREATE TABLE TBL_TRANS_LOCATIONS_HOP1
(
LOCATION_ID INT,
STREET_ADDRESS VARCHAR(45),
POSTAL_CODE VARCHAR(10),
CITY VARCHAR(25),
STATE_PROVINCE VARCHAR(25),
COUNTRY_ID VARCHAR(2)
); 
