DROP TABLE EMP_HIST;
DROP TABLE EMP;
DROP TABLE EMP_STG;

CREATE TABLE EMP_HIST
(ID INT, 
NAME VARCHAR(10),
ESALARY INT,
EDEPT VARCHAR(10));


CREATE TABLE EMP
(ID INT, 
NAME VARCHAR(10),
ESALARY INT,
EDEPT VARCHAR(10));


CREATE TABLE EMP_STG
(ID INT, 
NAME VARCHAR(10),
ESALARY INT,
EDEPT VARCHAR(10));


DELETE FROM EMP_HIST;
DELETE FROM EMP;
DELETE FROM EMP_STG;


SELECT * FROM EMP;


SELECT * FROM EMP_STG;
SELECT * FROM EMP_HIST;

INSERT INTO EMP_STG VALUES (1,'A',4000,'HR'),(2,'B',1200,'FIN'),(3,'C',5000,'SALES'),(4,'D',4000,'IT');
INSERT INTO EMP_STG VALUES (1,'A',2000,'HR'),(2,'B',1200,'HR'),(3,'C',5000,'HR'),(6,'D',4000,'SALES');
INSERT INTO EMP_STG VALUES (1,'A',2000,'EXEC');


SELECT COUNT(*)  FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);

CALL SP_TEST();

SELECT * FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);



/****STORED PROCEDURE****/

CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_Test`()
BEGIN
    DECLARE STG_COUNT INT;
	DECLARE EMP_COUNT INT;
	DECLARE EMP_HIST_COUNT INT;
	DECLARE DATA_AVAILABLE INT;
	
    
    SELECT COUNT(*) INTO STG_COUNT FROM EMP_STG;
	SELECT COUNT(*) INTO EMP_COUNT FROM EMP;
	SELECT COUNT(*) INTO EMP_HIST_COUNT FROM EMP_HIST;
	SELECT COUNT(*) INTO DATA_AVAILABLE FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);
    
    IF DATA_AVAILABLE = 0 THEN
        INSERT INTO EMP SELECT * FROM EMP_STG;
	ELSIF DATA_AVAILABLE<>STG_COUNT THEN
		INSERT INTO EMP_HIST SELECT * FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);
		DELETE FROM EMP WHERE WHERE ID IN (SELECT ID FROM EMP_STG);
		INSERT INTO EMP SELECT * FROM EMP_STG;
	ELSIF DATA_AVAILABLE=STG_COUNT THEN
		INSERT INTO EMP_HIST SELECT * FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);
		DELETE FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);
		INSERT INTO EMP SELECT * FROM EMP_STG;
	ELSE
		INSERT INTO EMP_HIST SELECT * FROM EMP WHERE ID IN (SELECT ID FROM EMP_STG);
		DELETE FROM EMP;
		INSERT INTO EMP SELECT * FROM EMP_STG;
    END IF;
 